### ISSUE TITLE
CSS: We need a way to remove the border-radius

### ISSUE THREAD

**Issue by bobaaaaa** [stroeer/stroeer-videoplayer#14]
For the new t-online.de we use the videoplayer as an opener for articles with videos. Our design systems does not need the border-radius for this 'position'. See designs:

<img width="344" alt="Bildschirmfoto 2021-09-29 um 08 58 22" src="https://user-images.githubusercontent.com/733158/135218728-16f366f2-b497-4459-be67-eae62204f0d7.png">

<img width="900" alt="Bildschirmfoto 2021-09-29 um 08 58 32" src="https://user-images.githubusercontent.com/733158/135218746-358f618e-d9a4-418c-927c-a1083d1c319d.png">

Is it possible to remove the `border-radius` via setting/config or should we do it by ourselves?

**Comment by ennoStroeer** [comment]
Since this is controlled by CSS, which is config by itself and due to the Cascade, i would suggest you overrule that with your CSS.
No need to burden the player with unnecessary config layers.
And - as far as i experienced - this is the most popular way to solve those issues. Every embedded widget has its own CSS which propably behaves different in different environments and must be adjusted by the environmental CSS.

**Comment by bobaaaaa** [comment]
👍
